steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gen_media/gen-media-demo:$COMMIT_SHA'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_API_KEY=AIzaSyCjwyHh8gH8SXcIYrWxrMpf72SIE5AaNJ4'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_AUTH_DOMAIN=strong-kit-475107-k1.firebaseapp.com'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_PROJECT_ID=strong-kit-475107-k1'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_STORAGE_BUCKET=strong-kit-475107-k1.firebasestorage.app'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID=929980771057'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_APP_ID=1:929980771057:web:ba4ebd8081c9ceceb1d750'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_MEASUREMENT_ID=G-GDV2NJ0VT8'
      - '.'

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gen_media/gen-media-demo:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'gen-media-demo'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gen_media/gen-media-demo:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gen_media/gen-media-demo:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
